api/controllers/entrance/send-password-recovery-email.js
https://www.notion.so/goodparty/Update-Reset-PW-email-template-2c62f9f09e3b47f982ee2441114a894c
=> update reset password email template

api/controllers/topIssues/topIssue/create.js, api/controllers/topIssues/topIssue/delete.js, api/controllers/topIssues/topIssue/update.js, api/helpers/s3-delete-file.js, api/helpers/s3-uploader.js, api/helpers/svg-uploader.js, api/models/candidates/TopIssue.js
API CRUD  implementation for https://goodparty.atlassian.net/browse/WEB-1450
=> Web 1450 top issues icons support

api/controllers/topIssues/topIssue/create.js, api/controllers/topIssues/topIssue/update.js
Updated the create/update endpoints to support md5 unique file names, and to return created/updated resource on response
=> [WEB-1450]

api/controllers/campaign/ballotData/races.js
https://goodparty.atlassian.net/browse/WEB-1770
=> [WEB-1770] - Nixed POTUS & VPOTUS from the query results

api/controllers/campaign/ballotData/races.js
https://goodparty.atlassian.net/browse/WEB-1696
**DO NOT MERGE WITHOUT WEB COMPANION PR MERGED!!!**
Companion PR:  https://github.com/thegoodparty/gp-webapp/pull/137
=> [WEB-1696] - (BREAKING_CHANGE) Grouped races by election date up to 4 years out from the present

api/controllers/campaign/onboarding/admin-update.js, api/models/campaign/Campaign.js
https://goodparty.atlassian.net/browse/WEB-1807
Companion WEB PR: https://github.com/thegoodparty/gp-webapp/pull/140
=> [WEB-1807] - Made field nullable

api/controllers/campaign/onboarding/admin-update.js, api/models/campaign/Campaign.js
Companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/142
=> [WEB-1808] - model changes for new tier column

api/controllers/campaign/onboarding/admin-update.js, api/controllers/entrance/social-login.js, api/helpers/crm/update-campaign.js, api/models/campaign/Campaign.js
https://goodparty.atlassian.net/browse/WEB-1796
Companion WEB PR: https://github.com/thegoodparty/gp-webapp/pull/145
=> [WEB-1796] - add date verified column

api/helpers/crm/update-campaign.js
https://goodparty.atlassian.net/browse/WEB-1841
=> [WEB-1841] - adds fields to HubSpot company objects

api/helpers/crm/update-campaign.js
https://goodparty.atlassian.net/browse/WEB-1839
=> [WEB-1839] - sends `isPro` field to HubSpot

api/controllers/content/update.js, api/helpers/contentful.js
API changes needed for this ticket: https://goodparty.atlassian.net/browse/WEB-1872
=> [WEB-1872] - CMS changes needed for client part of this ticket

api/controllers/admin/mass-crm-companies-refresh.js, api/helpers/crm/get-crm-company-object.js
https://goodparty.atlassian.net/browse/WEB-1896?focusedCommentId=12933
=> [WEB-1896] - Adds all of P2V fields to HubSpot values

api/controllers/campaign/doorKnocking/download.js, api/controllers/campaign/election-events.js, api/helpers/mailgun/mailgun-template-sender.js, api/policies/isAuthorizedCron.js, api/utils/campaign/event-handlers/findActionNeededCampaigns.js, api/utils/campaign/event-handlers/handleCancelCampaign.js, api/utils/campaign/event-handlers/sendAfterElectionEmail.js, api/utils/campaign/event-handlers/sendDayAfterPrimaryEmail.js, api/utils/campaign/event-handlers/sendProSubscriptionEndingEmail.js, api/utils/campaign/setUserCampaignIsPro.js, api/utils/email/sendElectionEventEmail.js, api/utils/payments/cancelCampaignProSubscription.js, api/utils/payments/webhookHandlers/checkoutSessionCompletedEventHandler.js, api/utils/payments/webhookHandlers/endCampaignProSubscription.js, config/policies.js, config/routes.js
companion webapp PR: https://github.com/thegoodparty/gp-webapp/pull/199
=> [WEB-2248][WEB-2490][WEB-2253] - implements endpointt for processing campaign events for daily cron

api/utils/payments/webhookHandlers/endCampaignProSubscription.js
Fix for https://goodparty.atlassian.net/browse/WEB-2266?focusedCommentId=13660
=> [WEB-2266] - Fix for https://goodparty.atlassian.net/browse/WEB-2266?focusedCommentId=13660

api/controllers/campaign/ein-support-document-upload.js, api/utils/campaign/get-ein-support-document-filename.js, api/utils/campaign/get-ein-support-document-folder-name.js, api/utils/upload-single-file-to-s3.js
companion UX PR: https://github.com/thegoodparty/gp-webapp/pull/213
=> [WEB-2474] - adds a unique folder for EIN docs to support prepopulating upload field

api/controllers/campaign/list.js
webapp PR: https://github.com/thegoodparty/gp-webapp/pull/228
=> [WEB-2535] - lastVisited and createdAt fix

api/controllers/payments/events.js, api/utils/campaign/campaignProSubscriptionUpdated.js
Webapp PR: https://github.com/thegoodparty/gp-webapp/pull/229
=> [WEB-2473] - Pending cancellation handling

api/controllers/content/update.js
Webapp PR: https://github.com/thegoodparty/gp-webapp/pull/230
=> [WEB-2169] - Preserve ordering in Team Members

api/controllers/content/update.js, api/helpers/contentful.js
webapp PR: https://github.com/thegoodparty/gp-webapp/pull/232
=> [WEB-2045] - new Terms of Service page and linking

api/controllers/campaign/delete-demo-campaign.js, api/controllers/user/metadata/get.js, config/routes.js
Campanion UI PR: https://github.com/thegoodparty/gp-webapp/pull/241
=> [WEB-2680] - Delete Demo Campaign Endpoint

api/controllers/campaign/create-demo-campaign.js, api/controllers/campaign/delete-demo-campaign.js
companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/243
=> [WEB-2726] - support for UX changes

api/controllers/campaign/update.js, api/controllers/user/files/generate-signed-upload-url.js, config/routes.js, package-lock.json, package.json
Web companion PR: https://github.com/thegoodparty/gp-webapp/pull/263
=> [WEB-2817] - New signed S3 upload URL endpoint

api/helpers/contentful.js
Updates the Contentful helper to pull in some new fields for blog content
=> WEB-2819: Blog: New Contentful Content

api/helpers/contentful.js
Pulls in a new Candidate Testimonial entity from Contentful to use in the Run for Office page.
=> WEB-2803: Pull in Candidate Testimonials from Contentful

api/helpers/contentful.js
Added a new field on the Contentful side to set FAQ links to display under Articles.
=> WEB-2862: Pull in FAQs field from Contentful blogHome entitiy

api/helpers/contentful.js
Small update to store image sizes when syncing data from Contentful
=> WEB-2909: Pull in image sizes from Contentful

api/controllers/voterData/voterFile/get.js, api/controllers/voterData/voterFile/schedule.js
**NOTE: this is based on #290, will need that merged first**
- Updates the Voter File link we send in a Text/Phone campaign slack message to include the campaign slug.
- Updates the Voter File get route to query the Campaign by slug if the current user is an admin
=> WEB-3209: Custom Voter File not Saving correctly

api/controllers/campaign/list.js, api/controllers/seed/campaigns.js
Adds a p2vStatus filter option to the campaigns-list route
=> WEB-3258: p2v status filter for campaigns

api/controllers/campaign/list-map-count.js
Backend component of https://github.com/thegoodparty/gp-webapp/pull/344
=> WEB-3306: Add ability to filter by win result to list-map-count

api/controllers/campaign/list-map-count.js, api/controllers/campaign/list-map.js
- Removes didWin === false filter
- Removes `'hubSpotUpdates'->>'verified_candidates' = 'Yes'` filter when querying for winners
- Moves electionDate filter to SQL query
=> fix: map winner count

api/controllers/campaign/ballotData/races.js, api/utils/campaign/searchMiscDistricts.js
Reverts thegoodparty/tgp-api#337
=> Revert "Qa"

api/controllers/campaign/ballotData/races.js
Reverts thegoodparty/tgp-api#331
=> Revert "New office picker"
